name: immowelt-hourly-test

on:
  schedule:
    - cron: "17 * * * *"   # каждый час на 17-й минуте; заработает после мержа в main
  workflow_dispatch:        # ручной запуск из вкладки Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show timestamp (UTC)
        run: echo "Run at (UTC): $(date -u +'%Y-%m-%d %H:%M:%S')"
