name: immowelt-hourly-test

on:
  schedule:
    - cron: "17 * * * *"  
  workflow_dispatch:       

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show timestamp (UTC)
        run: echo "Run at (UTC):$(date-u+'%Y-%m-%d %H:%M:%S')"
